version: '3'

services:
  scanner:
    build: .
    user: root
    restart: always
    ports:
      - "5000:5000"
    # command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/opt/scanner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - db

  nginx:
      image: nginx:stable
      restart: always
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - scanner
  
  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=scanner
      - MYSQL_USER=scanner
      - MYSQL_PASSWORD=scanner
      - MYSQL_DATABASE=scanner
    volumes:
      - .data/mysql:/var/lib/mysql

    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]